<?php

/** 
 * @file
 * Install, update, and uninstall functions for custom content types
 * 
 */

 function sasarchive_custom_content_types_install() {
    $sasarchive_custom_content_types_node_type = array(
        'type' => 'antonian',
        'name' => 'Antonian',
        'base' => 'node_content',
        'description' => t('Antonian Description'),
        'custom' => 1,
        'modified' => 1,
        'locked' => 0,
        'is_new' => TRUE,
        'settings' => array(
            'promote_enabled' => FALSE,
        ),
    );

    $sasarchive_custom_content_types_node_type = node_type_set_defaults($sasarchive_custom_content_types_node_type);
    node_type_save($sasarchive_custom_content_types_node_type);
    node_add_body_field($sasarchive_custom_content_types_node_type);
 }
 